import './styles.css';

document.querySelector('#root').innerHTML = `
<section id="login" class="login"><div class="login-box"><div class="logo"><span class="mark">L</span> LearnSpace</div><h1>Welcome back</h1><p>Use a seeded account to inspect the catalog and course player.</p><form id="loginForm"><label>Email<input id="email" type="email" value="priya@learnspace.dev" autocomplete="username" required></label><label>Password<input id="password" type="password" value="letmein123" autocomplete="current-password" required></label><span class="error" id="loginError"></span><button class="btn blue" style="width:100%">Sign in</button></form><div class="quick"><h4>Seeded accounts</h4><button class="seed" data-seed="student"><b>Priya Raman</b><small>priya@learnspace.dev · student</small></button><button class="seed" data-seed="admin"><b>Rio Fernandes</b><small>rio@learnspace.dev · admin</small></button></div></div></section>
<div id="app" class="hide"><header class="top"><div class="logo"><span class="mark">L</span> LearnSpace</div><nav class="nav"><button class="active" data-view="browse">Browse</button><button data-view="learning">My Learning</button></nav><label class="search">⌕ <input id="q" placeholder="Search courses"></label><div class="account"><div class="avatar" id="avatar">PR</div><div><b id="userName">Priya Raman</b><small id="userRole">Student</small></div><button class="btn outline small" id="logout">Sign out</button></div></header><main><section id="browse" class="view on"><div class="wrap"><div class="hero"><div><h1>Learn something <span>useful.</span></h1></div><p>A demo catalog of practical courses, with lesson links checked before playback.</p></div><div class="stats"><div class="stat"><b>500</b><small>courses in this demo catalog</small></div><div class="stat"><b>10</b><small>learning areas</small></div><div class="stat"><b id="verifiedStat">0</b><small>links checked in this session</small></div></div><div class="filters" id="filters"></div><div class="toolbar"><label>Price <select id="price"><option value="all">All</option><option value="free">Free</option><option value="paid">Paid</option></select></label><label>Level <select id="level"><option value="all">All</option><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select></label><label>Sort <select id="sort"><option value="popular">Popular</option><option value="rating">Rating</option><option value="low">Price low</option><option value="high">Price high</option></select></label><span class="count" id="count"></span></div><div class="verify"><strong>Video link check</strong><span id="verifyText">Checking a sample before playback is enabled.</span><span class="state" id="verifyState">0 / 500</span><button class="btn outline small" id="verifyAll">Verify all links</button></div><div id="rows" class="rows"></div><div id="more"></div></div></section><section id="course" class="view"><div class="wrap"><button class="back" id="back">← Back to catalog</button><div id="courseBody"></div></div></section><section id="learning" class="view"><div class="wrap"><div class="hero"><h1>Keep <span>going.</span></h1><p>Courses you have unlocked appear here.</p></div><div id="learningRows" class="learning"></div></div></section></main></div><div id="toast"></div>
`;


const USERS={student:{email:'priya@learnspace.dev',password:'letmein123',name:'Priya Raman',role:'Student'},admin:{email:'rio@learnspace.dev',password:'letmein123',name:'Rio Fernandes',role:'Admin'}};
const pools={Development:['JavaScript','TypeScript','React','Node.js','Python','Go','Rust','Java','Flutter','GraphQL'],Data:['SQL','Pandas','Statistics','Machine Learning','PyTorch','Data Engineering','A/B Testing','NLP'],Design:['Figma','Typography','UX Research','Design Systems','Motion Design','Accessibility'],Business:['Product Management','Strategy','Finance','Leadership','Negotiation','Operations'],Marketing:['SEO','Copywriting','Email Marketing','Growth','Brand Positioning'],Cloud:['AWS','Docker','Kubernetes','Terraform','Linux','CI/CD'],Security:['Web Security','Cryptography','Ethical Hacking','Cloud Security'],Language:['Spanish','French','German','Japanese','Mandarin'],Creative:['Photography','Video Editing','Music Production','Writing','Animation'],Growth:['Productivity','Deep Work','Career Change','Personal Finance','Interviewing']};
const videoIds=['PkZNo7MFNFg','W6NZfCO5SIk','hdI2bqOjy3c','kUMe1FH4CHE','rfscVS0vtbw','_uQrJ0TkZlc','8DvywoWv6fI','HXV3zeQKqGY','7S_tz1z_5bA','RBSGKlAvoiM','V_xro1bcAuA','aircAruvnKk','Ilg3gGewQ5U','IHZwWFHWa-w','fNk_zzaMoSs','RGOj5yH7evk','0IAPZzGSbME','bMknfKXIFA8','SqcY0GlETPk','Ke90Tje7VS0'];
const teachers=['Ana Petrova','Dmitri Sokolov','Marisol Duarte','Ife Adeyemi','Keiko Tan','Rio Fernandes','Lucía Moreno','Aisha Rahman','Wei Zhang','Elena Vasquez','Kwame Mensah','Mei Chen'];const angles=['from Scratch','The Complete Guide','Practical Workshop','Deep Dive','Patterns and Pitfalls','for Busy People','Build Real Projects','Fundamentals'];let seed=81;const rand=()=>{seed=(seed*9301+49297)%233280;return seed/233280};const courses=[];const cats=Object.keys(pools);for(let i=0;i<500;i++){let cat=cats[i%cats.length],subject=pools[cat][Math.floor(i/cats.length)%pools[cat].length],title=subject+' '+angles[Math.floor(i/30)%angles.length],price=i%3===0?0:[19,29,39,49,59,79][i%6],lessons=[];for(let j=0;j<5+i%6;j++)lessons.push({title:['The mental model','Core skills','A practical workflow','Common mistakes','Testing the result','Project walkthrough','Going further','Shipping your work','Final challenge'][j],id:videoIds[(i*3+j)%videoIds.length],duration:(6+(i+j)%10)+':'+String((i*13+j*7)%60).padStart(2,'0'),verified:false});courses.push({id:'c'+i,title,cat,teacher:teachers[i%teachers.length],price,level:['Beginner','Intermediate','Advanced'][i%3],rating:(4+(i%10)/10).toFixed(1),students:350+(i*977)%49000,lessons,desc:'A focused '+subject+' course built around practical work. Learn the concepts, avoid common traps, and finish with something you can show.'})}
let user=null,cat='All',shown=25,current=null,enrolled=new Set(['c3','c19','c42']),verified=0;const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function toast(t){$('#toast').innerHTML='<div class="toast">'+t+'</div>';setTimeout(()=>$('#toast').innerHTML='',2400)}
function enter(u){user=u;$('#login').classList.add('hide');$('#app').classList.remove('hide');$('#userName').textContent=u.name;$('#userRole').textContent=u.role;$('#avatar').textContent=u.name.split(' ').map(x=>x[0]).join('').slice(0,2);render()}
$('#loginForm').onsubmit=e=>{e.preventDefault();let u=Object.values(USERS).find(x=>x.email===$('#email').value.trim().toLowerCase()&&x.password===$('#password').value);if(!u){$('#loginError').textContent='Incorrect credentials. Use one of the seeded accounts below.';return}$('#loginError').textContent='';enter(u)};$$('[data-seed]').forEach(b=>b.onclick=()=>enter(USERS[b.dataset.seed]));$('#logout').onclick=()=>{$('#app').classList.add('hide');$('#login').classList.remove('hide')};
$('#filters').innerHTML=['All',...cats].map(x=>'<button class="chip '+(x==='All'?'active':'')+'" data-cat="'+x+'">'+x+'</button>').join('');$$('[data-cat]').forEach(b=>b.onclick=()=>{cat=b.dataset.cat;shown=25;$$('[data-cat]').forEach(x=>x.classList.toggle('active',x===b));render()});['price','level','sort'].forEach(id=>$('#'+id).onchange=()=>{shown=25;render()});$('#q').oninput=()=>{shown=25;render()};
function filtered(){let q=$('#q').value.trim().toLowerCase(),p=$('#price').value,l=$('#level').value,a=courses.filter(c=>(cat==='All'||c.cat===cat)&&(p==='all'||(p==='free'?c.price===0:c.price>0))&&(l==='all'||c.level===l)&&(!q||(c.title+' '+c.cat+' '+c.teacher).toLowerCase().includes(q)));let s=$('#sort').value;a.sort(s==='rating'?(x,y)=>y.rating-x.rating:s==='low'?(x,y)=>x.price-y.price:s==='high'?(x,y)=>y.price-x.price:(x,y)=>y.students-x.students);return a}
function row(c,i){return '<button class="row" data-open="'+c.id+'"><span class="num">'+String(i+1).padStart(3,'0')+'</span><span><h3>'+c.title+'</h3><span class="meta">★ '+c.rating+' · '+c.teacher+' · '+c.cat+' · '+c.lessons.length+' lessons <span class="tag '+(c.price?'paid':'free')+'">'+(c.price?'Paid':'Free')+'</span></span></span><span class="cost">'+(c.price?'$'+c.price:'Free')+'</span><span class="arrow">→</span></button>'}
function render(){let a=filtered();$('#count').textContent=Math.min(shown,a.length)+' of '+a.length;$('#rows').innerHTML=a.slice(0,shown).map(row).join('');$('#more').innerHTML=shown<a.length?'<div class="more"><button class="btn outline" id="load">Load 25 more</button><small>'+(a.length-shown)+' courses left</small></div>':'<div class="more"><small>End of results</small></div>';$$('[data-open]').forEach(b=>b.onclick=()=>openCourse(courses.find(c=>c.id===b.dataset.open)));if($('#load'))$('#load').onclick=()=>{shown+=25;render()};$('#verifyState').textContent=verified+' / 500';$('#verifiedStat').textContent=verified;}
async function checkVideo(l){if(l.verified)return true;let url='https://www.youtube.com/oembed?url='+encodeURIComponent('https://www.youtube.com/watch?v='+l.id)+'&format=json';try{let r=await fetch(url,{mode:'cors'});l.verified=r.ok;return l.verified}catch(e){return false}}
async function verifyBatch(list){let n=0;for(let i=0;i<list.length;i+=8){await Promise.all(list.slice(i,i+8).map(async c=>{let ok=await Promise.all(c.lessons.map(checkVideo));if(ok.every(Boolean))n++;}));verified=Math.min(500,verified+Math.min(8,list.length-i));$('#verifyText').textContent='Checking course links against YouTube oEmbed metadata.';render()}}
$('#verifyAll').onclick=async()=>{let b=$('#verifyAll');b.disabled=true;b.textContent='Verifying…';await verifyBatch(courses);b.textContent='Verified';toast('Link check complete. Playback only opens verified videos.');};
function openCourse(c){if(!c)return;current=c;show('course');renderCourse(0);requestAnimationFrame(()=>window.scrollTo({top:0,behavior:'smooth'}))}function show(id){$$('.view').forEach(v=>v.classList.toggle('on',v.id===id));$$('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id))}$$('.nav button').forEach(b=>b.onclick=()=>{show(b.dataset.view);if(b.dataset.view==='learning')renderLearning()});$('#back').onclick=()=>show('browse');
function renderCourse(i){let c=current,l=c.lessons[i],paid=c.price>0,unlocked=enrolled.has(c.id);$('#courseBody').innerHTML='<div class="course"><div><div class="player" id="player"><div class="video-title"><span>Lesson '+(i+1)+': '+l.title+'</span></div>'+(!unlocked&&paid?'<div class="notice"><div class="notice-box"><div class="lock">🔒</div><h3>Payment required</h3><p>This paid course stays locked until enrollment is complete. No video request is made.</p><button class="btn blue" id="pay">Pay $'+c.price+' and enroll</button></div></div>':'<button class="center" id="play">▶</button>')+'</div><h1>'+c.title+'</h1><p class="blurb">'+c.desc+'</p><div class="lessons"><h3>'+c.lessons.length+' lessons</h3>'+c.lessons.map((x,j)=>'<button class="lesson '+(j===i?'active':'')+'" data-lesson="'+j+'"><span class="n">'+String(j+1).padStart(2,'0')+'</span><span>'+x.title+'</span><span class="time">'+x.duration+'</span></button>').join('')+'</div></div><aside class="side"><div class="price">'+(c.price?'$'+c.price:'Free')+'</div><button class="btn blue" id="enroll" style="width:100%">'+(unlocked?'Continue course':c.price?'Pay and enroll':'Enroll free')+'</button><ul><li>Lessons <b>'+c.lessons.length+'</b></li><li>Level <b>'+c.level+'</b></li><li>Access <b>Lifetime</b></li><li>Playback <b>Verified only</b></li></ul></aside></div>';$$('[data-lesson]').forEach(b=>b.onclick=()=>renderCourse(+b.dataset.lesson));if($('#pay'))$('#pay').onclick=()=>{enrolled.add(c.id);toast('Demo payment complete. Course unlocked.');renderCourse(i)};$('#enroll').onclick=()=>{enrolled.add(c.id);toast(c.price?'Demo payment complete. Course unlocked.':'Enrolled successfully.');renderCourse(i)};if($('#play'))$('#play').onclick=async()=>{if(c.price&&!enrolled.has(c.id))return;let ok=await checkVideo(l);if(!ok){toast('This lesson link did not verify, so playback is blocked.');return}let u='https://www.youtube-nocookie.com/embed/'+l.id+'?autoplay=1&rel=0';$('#player').innerHTML='<iframe src="'+u+'" allow="autoplay; encrypted-media; picture-in-picture" allowfullscreen title="'+l.title+'"></iframe>'}}
function renderLearning(){let a=courses.filter(c=>enrolled.has(c.id));$('#learningRows').innerHTML=a.map((c,i)=>'<div class="learn-row"><div><h3>'+c.title+'</h3><div class="progress"><i style="width:'+(25+i*19)+'%"></i></div></div><button class="btn blue small" data-learn="'+c.id+'">Continue</button></div>').join('')||'<div class="empty">No courses yet. Enroll in a free course to start.</div>';$$('[data-learn]').forEach(b=>b.onclick=()=>openCourse(courses.find(c=>c.id===b.dataset.learn)))}
render();verifyBatch(courses.slice(0,8));
